<?php
/**
 * DepartureTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DepartureTest Class Doc Comment
 *
 * @category    Class
 * @description Departure
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DepartureTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Departure"
     */
    public function testDeparture()
    {
    }

    /**
     * Test attribute "fg_color"
     */
    public function testPropertyFgColor()
    {
    }

    /**
     * Test attribute "stop"
     */
    public function testPropertyStop()
    {
    }

    /**
     * Test attribute "booking"
     */
    public function testPropertyBooking()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "journey_detail_ref"
     */
    public function testPropertyJourneyDetailRef()
    {
    }

    /**
     * Test attribute "track"
     */
    public function testPropertyTrack()
    {
    }

    /**
     * Test attribute "rt_track"
     */
    public function testPropertyRtTrack()
    {
    }

    /**
     * Test attribute "sname"
     */
    public function testPropertySname()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "bg_color"
     */
    public function testPropertyBgColor()
    {
    }

    /**
     * Test attribute "stroke"
     */
    public function testPropertyStroke()
    {
    }

    /**
     * Test attribute "rt_date"
     */
    public function testPropertyRtDate()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "rt_time"
     */
    public function testPropertyRtTime()
    {
    }

    /**
     * Test attribute "night"
     */
    public function testPropertyNight()
    {
    }

    /**
     * Test attribute "stopid"
     */
    public function testPropertyStopid()
    {
    }

    /**
     * Test attribute "journeyid"
     */
    public function testPropertyJourneyid()
    {
    }

    /**
     * Test attribute "accessibility"
     */
    public function testPropertyAccessibility()
    {
    }
}
