<?php
/**
 * DestinationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DestinationTest Class Doc Comment
 *
 * @category    Class
 * @description Destination
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DestinationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Destination"
     */
    public function testDestination()
    {
    }

    /**
     * Test attribute "route_idx"
     */
    public function testPropertyRouteIdx()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "cancelled"
     */
    public function testPropertyCancelled()
    {
    }

    /**
     * Test attribute "track"
     */
    public function testPropertyTrack()
    {
    }

    /**
     * Test attribute "rt_track"
     */
    public function testPropertyRtTrack()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "rt_date"
     */
    public function testPropertyRtDate()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "directdate"
     */
    public function testPropertyDirectdate()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "rt_time"
     */
    public function testPropertyRtTime()
    {
    }

    /**
     * Test attribute "directtime"
     */
    public function testPropertyDirecttime()
    {
    }
}
