<?php
/**
 * JourneyDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JourneyDetailTest Class Doc Comment
 *
 * @category    Class
 * @description JourneyDetail
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JourneyDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JourneyDetail"
     */
    public function testJourneyDetail()
    {
    }

    /**
     * Test attribute "journey_type"
     */
    public function testPropertyJourneyType()
    {
    }

    /**
     * Test attribute "error_text"
     */
    public function testPropertyErrorText()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "serverdate"
     */
    public function testPropertyServerdate()
    {
    }

    /**
     * Test attribute "servertime"
     */
    public function testPropertyServertime()
    {
    }

    /**
     * Test attribute "journey_id"
     */
    public function testPropertyJourneyId()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "stop"
     */
    public function testPropertyStop()
    {
    }

    /**
     * Test attribute "journey_name"
     */
    public function testPropertyJourneyName()
    {
    }

    /**
     * Test attribute "geometry_ref"
     */
    public function testPropertyGeometryRef()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "no_namespace_schema_location"
     */
    public function testPropertyNoNamespaceSchemaLocation()
    {
    }
}
