<?php
/**
 * LegTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LegTest Class Doc Comment
 *
 * @category    Class
 * @description Leg
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LegTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Leg"
     */
    public function testLeg()
    {
    }

    /**
     * Test attribute "fg_color"
     */
    public function testPropertyFgColor()
    {
    }

    /**
     * Test attribute "booking"
     */
    public function testPropertyBooking()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "journey_detail_ref"
     */
    public function testPropertyJourneyDetailRef()
    {
    }

    /**
     * Test attribute "cancelled"
     */
    public function testPropertyCancelled()
    {
    }

    /**
     * Test attribute "kcal"
     */
    public function testPropertyKcal()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "sname"
     */
    public function testPropertySname()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "geometry_ref"
     */
    public function testPropertyGeometryRef()
    {
    }

    /**
     * Test attribute "bg_color"
     */
    public function testPropertyBgColor()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "stroke"
     */
    public function testPropertyStroke()
    {
    }

    /**
     * Test attribute "reachable"
     */
    public function testPropertyReachable()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "night"
     */
    public function testPropertyNight()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "percent_bike_road"
     */
    public function testPropertyPercentBikeRoad()
    {
    }

    /**
     * Test attribute "accessibility"
     */
    public function testPropertyAccessibility()
    {
    }
}
