<?php
/**
 * LiveMapTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LiveMapTest Class Doc Comment
 *
 * @category    Class
 * @description LiveMap
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LiveMapTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LiveMap"
     */
    public function testLiveMap()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "maxx"
     */
    public function testPropertyMaxx()
    {
    }

    /**
     * Test attribute "maxy"
     */
    public function testPropertyMaxy()
    {
    }

    /**
     * Test attribute "vehicles"
     */
    public function testPropertyVehicles()
    {
    }

    /**
     * Test attribute "minx"
     */
    public function testPropertyMinx()
    {
    }

    /**
     * Test attribute "miny"
     */
    public function testPropertyMiny()
    {
    }
}
