<?php
/**
 * LocationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LocationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAllStops
     *
     * Returns a list of all stops available in the journey planner..
     *
     */
    public function testGetAllStops()
    {
    }

    /**
     * Test case for getLocationByName
     *
     * Returns a list of possible matches in the journey planner database.
     *
     */
    public function testGetLocationByName()
    {
    }

    /**
     * Test case for getNearbyAddress
     *
     * Returns the address nearest a given coordinate..
     *
     */
    public function testGetNearbyAddress()
    {
    }

    /**
     * Test case for getNearbyStops
     *
     * Returns a list of stops around a given center coordinate..
     *
     */
    public function testGetNearbyStops()
    {
    }
}
