<?php
/**
 * StopTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StopTest Class Doc Comment
 *
 * @category    Class
 * @description Stop
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StopTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Stop"
     */
    public function testStop()
    {
    }

    /**
     * Test attribute "route_idx"
     */
    public function testPropertyRouteIdx()
    {
    }

    /**
     * Test attribute "arr_date"
     */
    public function testPropertyArrDate()
    {
    }

    /**
     * Test attribute "dep_time"
     */
    public function testPropertyDepTime()
    {
    }

    /**
     * Test attribute "lon"
     */
    public function testPropertyLon()
    {
    }

    /**
     * Test attribute "dep_date"
     */
    public function testPropertyDepDate()
    {
    }

    /**
     * Test attribute "track"
     */
    public function testPropertyTrack()
    {
    }

    /**
     * Test attribute "rt_track"
     */
    public function testPropertyRtTrack()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "rt_dep_time"
     */
    public function testPropertyRtDepTime()
    {
    }

    /**
     * Test attribute "rt_arr_time"
     */
    public function testPropertyRtArrTime()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "arr_time"
     */
    public function testPropertyArrTime()
    {
    }

    /**
     * Test attribute "lat"
     */
    public function testPropertyLat()
    {
    }

    /**
     * Test attribute "rt_dep_date"
     */
    public function testPropertyRtDepDate()
    {
    }

    /**
     * Test attribute "rt_arr_date"
     */
    public function testPropertyRtArrDate()
    {
    }
}
