<?php
/**
 * SystemInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SystemInfoTest Class Doc Comment
 *
 * @category    Class
 * @description SystemInfo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SystemInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SystemInfo"
     */
    public function testSystemInfo()
    {
    }

    /**
     * Test attribute "timetable_info"
     */
    public function testPropertyTimetableInfo()
    {
    }

    /**
     * Test attribute "error_text"
     */
    public function testPropertyErrorText()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "serverdate"
     */
    public function testPropertyServerdate()
    {
    }

    /**
     * Test attribute "servertime"
     */
    public function testPropertyServertime()
    {
    }

    /**
     * Test attribute "no_namespace_schema_location"
     */
    public function testPropertyNoNamespaceSchemaLocation()
    {
    }
}
