<?php
/**
 * VehicleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reseplaneraren
 *
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VehicleTest Class Doc Comment
 *
 * @category    Class
 * @description Vehicle
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VehicleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Vehicle"
     */
    public function testVehicle()
    {
    }

    /**
     * Test attribute "lcolor"
     */
    public function testPropertyLcolor()
    {
    }

    /**
     * Test attribute "prod_class"
     */
    public function testPropertyProdClass()
    {
    }

    /**
     * Test attribute "bcolor"
     */
    public function testPropertyBcolor()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "gid"
     */
    public function testPropertyGid()
    {
    }

    /**
     * Test attribute "delay"
     */
    public function testPropertyDelay()
    {
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
    }
}
